name             'stns'
maintainer       'pyama86'
maintainer_email 'www.kazu.com@gmail.com'
issues_url        'https://github.com/STNS/stns-cookbook/issues'
source_url        'https://github.com/STNS/stns-cookbook/'
license          'All rights reserved'
description      'Installs/Configures stns'
version          '0.1.0'
depends          'nscd'

