FROM ubuntu:jammy
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update -qqy && apt -qqy install \
  init \
  curl \
  net-tools \
  ruby \
  ruby-dev \
  rsyslog \
  systemd \
  lsb-release \
  build-essential \
  git \
  tzdata

RUN gem install bundler
ARG CHEF_VERSION
RUN curl -L -O http://downloads.cinc.sh/files/stable/cinc/$CHEF_VERSION/debian/11/cinc_$CHEF_VERSION-1_amd64.deb
RUN dpkg -i cinc_$CHEF_VERSION-1_amd64.deb
